### ISSUE TITLE
Uppercase only in HTML View can cause issues!

### ISSUE THREAD

**Issue by DarrenNavitas** [Gh61/WYSitor#1]
Firstly - thanks for creating this - had lots of problems using the SmithHTML editor - and then found this and it works well.

Just wanted to point out one issue - in the HTML view any text entered is is uppercase only.  This cause an issue for a user when they were manually trying to provide a the source to an img file which was hosted on a wordpress site - and very particular that the URL was in lowercase or wouldn't provided a file not found error.

**Comment by Gh61** [comment]
I'm glad that it's working for you. 

Can you create some Minimal reproducible example (ideally some small project containing the bug), as I cannot reproduce your issue.

**Comment by DarrenNavitas** [comment]
Please ignore me!   Issue found and resolved. Internal resource was setting all TextBlocks to uppercase - and this affected the source view.
