### ISSUE TITLE
Switching between WYSIWYG and HTML Editor nullifies the content

### ISSUE THREAD

**Issue by MahmudX** [Gh61/WYSitor#2]
First, thank you for this component. It's very lightweight and smooth. But there is an issue with the toggling between code and visual editor.

Please see the gif.

![Untitled video](https://user-images.githubusercontent.com/16564582/232261068-a87ab5bc-42a7-460d-8c0b-c16e2274d039.gif)

1. I pasted some html inside the html editor
2. I toggled to the WYSIWYG editor
3. Did nothing and toggled again
4. The HTML content is vanished
5. I pasted again (<kbd>CTRL+Z</kbd> also works)
6. Toggled to WYSIWYG
7. Did some changes
8. Toggled to code
9. everything fine
10. Followed 2 -> 4
11. Toggled to WYSIWYG without pasting the code
12. Program crashes 

This problem does not occur if I do not bring the code from outside. I think, Uppercased tag name is causing some issues.

**Comment by Gh61** [comment]
Thank you for discovering this issue.
Please give me the HTML code which is causing the problems, so I can reproduce exactly the issue.

Meanwhile I just fixed your other issue - introduced new property so you can turn on/off the overflow of Toolbar.
See the latest release.

**Comment by MahmudX** [comment]
```html
<!DOCTYPE html>
<html>
<head>
	<title>Welcome Email</title>
	<style>
		body {
			background-color: black;
			color: white;
			font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
			line-height: 1.5;
			padding: 0;
			margin: 0;
		}

		.container {
			max-width: 600px;
			margin: 0 auto;
			padding: 30px;
			background-color: #1b1b1b;
			border-radius: 10px;
			box-shadow: 0 0 10px 0 #000;
			margin-top: 30px;
			margin-bottom: 30px;
		}

		.logo {
			display: block;
			margin: 0 auto;
			width: 100px;
			height: 100px;
			background-image: url('https://www.yourwebsite.com/images/logo.png');
			background-size: cover;
			background-position: center;
			border-radius: 50%;
			margin-bottom: 30px;
		}

		h1 {
			font-size: 36px;
			font-weight: bold;
			margin-bottom: 20px;
			text-align: center;
			text-transform: uppercase;
			letter-spacing: 2px;
		}

		p {
			font-size: 16px;
			margin-bottom: 20px;
			text-align: center;
			line-height: 1.5;
		}

		.cta {
			display: block;
			margin: 0 auto;
			padding: 10px 20px;
			background-color: #ff0066;
			color: white;
			font-size: 18px;
			text-align: center;
			text-decoration: none;
			border-radius: 5px;
			margin-top: 30px;
			transition: all 0.2s ease-in-out;
		}

		.cta:hover {
			background-color: #990033;
			cursor: pointer;
		}
	</style>
</head>
<body>
	<div class="container">
		<div class="logo"></div>
		<h1>Welcome to Your Website</h1>
		<p>Thank you for signing up for our service. We're excited to have you on board and can't wait to see what you create.</p>
		<a href="#" class="cta">Get Started</a>
	</div>
</body>
</html>
```

Here you go.

**Comment by MahmudX** [comment]
If you add some sort of editor (i.e. [monaco](https://github.com/microsoft/monaco-editor) or [AvalonEdit](https://github.com/icsharpcode/AvalonEdit)) instead of plain text box, that would be great.  Also can you make the tag lower cased? 
@Gh61

**Comment by Gh61** [comment]
Thank you, the issue is now resolved (see latest release).
The cause was loading of external resources (background in your case).

As for code highlighting editor for source code mode - This project purpose is to create lightweight "wrapper" around WebBrowser interactive mode. Implementing this would destroy the initial idea.
If you want this advanced feature, you can create own toolbar button, that opens this kind of editor.

The same applies to lowercase tags. Uppercase tags goes (saldy) straight from the WebBrowser. If you want to transform the code somehow, it's up to you.

Thanks for your understanding
